"""DocuGen: Production-grade, local-first document intelligence and generation framework."""

from docugen.api.public import (
    ClassificationResult,
    Diagnostic,
    DigitalSignatureConfig,
    DocuGenConfig,
    DocuGenError,
    GenerationResult,
    RenderResult,
    RenderingError,
    SchemaError,
    TemplateError,
    TemplateNotFoundError,
    ValidationError,
    ValidationResult,
    amount_to_words,
    classify_document,
    format_currency,
    generate_clause,
    generate_document,
    generate_document_async,
    generate_documents_batch,
    generate_self_signed_certificate,
    get_default_config,
    get_schema,
    list_document_types,
    list_templates,
    preview_document,
    register_document_type,
    register_template,
    register_validator,
    set_default_config,
    sign_pdf_document,
    translate_term,
    validate_document_data,
    verify_pdf_signature,
)
from docugen.core.document_ir import (
    Alignment,
    BlockElement,
    ClauseIR,
    Document,
    DocumentMetadata,
    Footer,
    Header,
    Heading,
    ListBlock,
    ListItem,
    PageBreak,
    Paragraph,
    Section,
    SignatureBlock,
    Signer,
    Subsection,
    Table,
    TableCell,
    TableRow,
    BarcodeElement,
    QRCodeElement,
    Watermark,
)
from docugen.versioning.metadata import (
    GenerationMetadata,
    __import_name__,
    __package_name__,
    __version__,
)

__all__ = [
    # Top-level functions
    "generate_document",
    "generate_document_async",
    "generate_documents_batch",
    "validate_document_data",
    "classify_document",
    "generate_clause",
    "preview_document",
    "register_template",
    "register_document_type",
    "register_validator",
    "get_schema",
    "list_templates",
    "list_document_types",
    # Digital Signatures & Security
    "DigitalSignatureConfig",
    "sign_pdf_document",
    "verify_pdf_signature",
    "generate_self_signed_certificate",
    # i18n & Localization
    "amount_to_words",
    "format_currency",
    "translate_term",
    # Configuration
    "DocuGenConfig",
    "get_default_config",
    "set_default_config",
    # Models & Results
    "GenerationResult",
    "ValidationResult",
    "ClassificationResult",
    "RenderResult",
    "Diagnostic",
    "GenerationMetadata",
    # Exceptions
    "DocuGenError",
    "ValidationError",
    "SchemaError",
    "TemplateError",
    "TemplateNotFoundError",
    "RenderingError",
    # Document IR
    "Document",
    "DocumentMetadata",
    "Section",
    "Subsection",
    "Paragraph",
    "TextRun",
    "Heading",
    "ListBlock",
    "ListItem",
    "Table",
    "TableRow",
    "TableCell",
    "SignatureBlock",
    "Signer",
    "PageBreak",
    "Header",
    "Footer",
    "Watermark",
    "QRCodeElement",
    "BarcodeElement",
    "ClauseIR",
    "Alignment",
    "BlockElement",
    # Package info
    "__version__",
    "__package_name__",
    "__import_name__",
]
