"""Public API package for DocuGen AI."""

from docugen.api.public import (
    ClassificationResult,
    Diagnostic,
    DocuGenConfig,
    DocuGenError,
    GenerationResult,
    RenderResult,
    RenderingError,
    SchemaError,
    TemplateError,
    TemplateNotFoundError,
    ValidationError,
    ValidationResult,
    classify_document,
    generate_clause,
    generate_document,
    get_default_config,
    get_schema,
    list_document_types,
    list_templates,
    preview_document,
    register_document_type,
    register_template,
    register_validator,
    set_default_config,
)

__all__ = [
    "generate_document",
    "validate_document_data",
    "classify_document",
    "generate_clause",
    "preview_document",
    "register_template",
    "register_document_type",
    "register_validator",
    "get_schema",
    "list_templates",
    "list_document_types",
    "DocuGenConfig",
    "get_default_config",
    "set_default_config",
    "GenerationResult",
    "ValidationResult",
    "ClassificationResult",
    "RenderResult",
    "Diagnostic",
    "DocuGenError",
    "ValidationError",
    "SchemaError",
    "TemplateError",
    "TemplateNotFoundError",
    "RenderingError",
]
